apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fiap-videos-api-secrets
  namespace: fiap-videos
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fiap-videos-aws-secrets
    kind: ClusterSecretStore
  target:
    name: fiap-videos-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: fiap-videos/production/jwt-secret
    - secretKey: DATABASE_URL
      remoteRef:
        key: fiap-videos/production/api-database-url
    - secretKey: REDIS_URL
      remoteRef:
        key: fiap-videos/production/redis-url
    - secretKey: RABBITMQ_URL
      remoteRef:
        key: fiap-videos/production/rabbitmq-url
