apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fiap-videos-notifier-secrets
  namespace: fiap-videos
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fiap-videos-aws-secrets
    kind: ClusterSecretStore
  target:
    name: fiap-videos-notifier-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: fiap-videos/production/notifier-database-url
    - secretKey: RABBITMQ_URL
      remoteRef:
        key: fiap-videos/production/rabbitmq-url
    - secretKey: SMTP_HOST
      remoteRef:
        key: fiap-videos/production/smtp-config
        property: host
    - secretKey: SMTP_PORT
      remoteRef:
        key: fiap-videos/production/smtp-config
        property: port
    - secretKey: SMTP_FROM
      remoteRef:
        key: fiap-videos/production/smtp-config
        property: from
