apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fiap-videos-processor-secrets
  namespace: fiap-videos
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fiap-videos-aws-secrets
    kind: ClusterSecretStore
  target:
    name: fiap-videos-processor-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: fiap-videos/production/processor-database-url
    - secretKey: RABBITMQ_URL
      remoteRef:
        key: fiap-videos/production/rabbitmq-url
