apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - external-secrets
  - serviceaccounts

namePrefix: production-

replacements:
  - source:
      kind: ClusterSecretStore
      name: fiap-videos-aws-secrets
      fieldPath: metadata.name
    targets:
      - select:
          kind: ExternalSecret
        fieldPaths:
          - spec.secretStoreRef.name

images:
  - name: fiap-videos-api
    newName: REPLACE_AWS_ACCOUNT.dkr.ecr.us-east-2.amazonaws.com/fiap-videos-api
    newTag: latest
  - name: fiap-videos-processor
    newName: REPLACE_AWS_ACCOUNT.dkr.ecr.us-east-2.amazonaws.com/fiap-videos-processor
    newTag: latest
  - name: fiap-videos-notifier
    newName: REPLACE_AWS_ACCOUNT.dkr.ecr.us-east-2.amazonaws.com/fiap-videos-notifier
    newTag: latest

patches:
  - path: patches/api-deployment-sa.yaml
  - path: patches/processor-deployment-sa.yaml
  - path: patches/storage-config.yaml
  - path: patches/api-runtime-config.yaml
  - path: patches/notifier-runtime-config.yaml
  - path: patches/api-hpa.yaml
  - path: patches/processor-hpa.yaml
