apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fiap-videos

resources:
  - namespace.yaml
  - serviceaccounts/api-serviceaccount.yaml
  - serviceaccounts/processor-serviceaccount.yaml
  - config/storage-config.yaml
  - config/api-runtime-config.yaml
  - autoscaling/api-hpa.yaml
  - autoscaling/processor-hpa.yaml
  - api/deployment.yaml
  - processor/deployment.yaml
  - notifier/deployment.yaml
  - secrets/app-secrets.yaml
  - ingress/api-ingress.yaml
  - migration-jobs/api-migration.yaml
  - migration-jobs/processor-migration.yaml
  - migration-jobs/notifier-migration.yaml

commonLabels:
  app.kubernetes.io/part-of: fiap-videos
