apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fiap-videos-aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${AWS_REGION}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
