apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-secret-store.yaml
  - api-external-secret.yaml
  - processor-external-secret.yaml
  - notifier-external-secret.yaml
