apiVersion: v1
kind: Secret
metadata:
  name: fiap-videos-api-secrets
type: Opaque
stringData:
  JWT_SECRET: dev-secret-change-me
  DATABASE_URL: postgresql://fiap:fiap@postgres:5432/fiap_videos_api
  REDIS_URL: redis://redis:6379
  RABBITMQ_URL: amqp://fiap:fiap@rabbitmq:5672/
