apiVersion: v1
kind: Secret
metadata:
  name: fiap-videos-notifier-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql://fiap:fiap@postgres:5432/fiap_videos_notifier
  RABBITMQ_URL: amqp://fiap:fiap@rabbitmq:5672/
  SMTP_HOST: mailhog
  SMTP_PORT: "1025"
  SMTP_FROM: noreply@fiap-videos.local
