apiVersion: v1
kind: Secret
metadata:
  name: fiap-videos-processor-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql://fiap:fiap@postgres:5432/fiap_videos_processor
  RABBITMQ_URL: amqp://fiap:fiap@rabbitmq:5672/
