apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - external-secrets
  - serviceaccounts

namePrefix: staging-

replacements:
  - source:
      kind: ClusterSecretStore
      name: fiap-videos-aws-secrets
      fieldPath: metadata.name
    targets:
      - select:
          kind: ExternalSecret
        fieldPaths:
          - spec.secretStoreRef.name

images:
  - name: fiap-videos-api
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/fiap-videos-api
    newTag: latest-staging
  - name: fiap-videos-processor
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/fiap-videos-processor
    newTag: latest-staging
  - name: fiap-videos-notifier
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/fiap-videos-notifier
    newTag: latest-staging
  - name: fiap-videos-api-migrator
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/fiap-videos-api
    newTag: migrator-staging
  - name: fiap-videos-processor-migrator
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/fiap-videos-processor
    newTag: migrator-staging
  - name: fiap-videos-notifier-migrator
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/fiap-videos-notifier
    newTag: migrator-staging

patches:
  - path: patches/api-deployment.yaml
  - path: patches/processor-deployment.yaml
  - path: patches/notifier-deployment.yaml
  - path: patches/api-hpa.yaml
  - path: patches/processor-hpa.yaml
  - path: patches/api-deployment-sa.yaml
  - path: patches/processor-deployment-sa.yaml
  - path: patches/storage-config.yaml
  - path: patches/api-runtime-config.yaml
  - path: patches/notifier-runtime-config.yaml
  - path: ingress-patch.yaml
